### ISSUE TITLE
Experimental Configurations in LAMBDA

### ISSUE THREAD

**Issue by lllbbbyyy** [Haimrich/medea#1]
Hello, I had the privilege of reading your paper on LAMBDA. I would like to perform some simulations on chiplet systems using your platform. Therefore, I would like to start by reproducing the configurations mentioned in your LAMBDA paper. However, I couldn't seem to find the configuration files for the experimental section in this repository. Could you please let me know where I can find them? I will also cite your LAMBDA in my future research work. Thank you very much!

**Comment by Haimrich** [comment]
Hello, thank you very much for the interest in our research.

This is the MEDEA repository, you can find the LAMBDA repository [here](https://github.com/Haimrich/timeloop).
Regarding configuration files for LAMBDA, please find [here](https://github.com/Haimrich/medea/files/12651963/lambda_data.zip) some files very similar to the ones used for experiments.

Thanks,
Enrico

**Comment by lllbbbyyy** [comment]
Thank you very much! I apologize for the confusion earlier because I was comparing the architecture configurations provided by two repositories, and I made a mistake regarding the issue area. The configuration you provided has been very helpful to me! 

After carefully reading the LAMBDA paper and conducting experiments, I have a point of confusion. It seems that the maximum cycle among MAC/NOC/NOP/RAM is considered as the delay. Why isn't the delay the sum of these values? Is it because of the overlap between computation and communication, and the fact that the two parts are computed separately, that the maximum value is closer to the true value than the sum?

**Comment by Haimrich** [comment]
Yes exactly. Communication and computation are assumed to overlap due to double buffering. Therefore, the overall delay is determined by the slowest component that will force the others to wait

**Comment by lllbbbyyy** [comment]
I understand. Thank you once again for your patient response!
